//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int BookID { get; set; }
        public string BookTitle { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public string BookContent { get; set; }
        public Nullable<int> AuthorID { get; set; }
    
        public virtual Authors Authors { get; set; }
    }
}
